"""empty message

Revision ID: 244aded8df9d
Revises: 2370ffae2c50
Create Date: 2021-07-29 00:39:11.939144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244aded8df9d'
down_revision = '2370ffae2c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('material_documentations', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_documentations', 'created_at')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
