"""empty message

Revision ID: 7775ae9ec660
Revises: 244aded8df9d
Create Date: 2021-08-03 12:28:21.365948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7775ae9ec660'
down_revision = '244aded8df9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_documentations', sa.Column('citation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_documentations', 'citation')
    # ### end Alembic commands ###
